Repository MissingCore/Music, pull requests merged in 2024-12, with the labels that each got.

#113 chore: Playback Service Adjustments
  mobile/index.ts
  mobile/src/app/(main)/(home)/index.tsx
  mobile/src/hooks/useHasHydratedStores.ts
  mobile/src/lib/zustand.ts
  mobile/src/modules/media/helpers/data.ts
  mobile/src/modules/media/services/Music.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/modules/media/services/RecentList.ts
  mobile/src/modules/media/services/Resynchronize.ts
  mobile/src/modules/media/types.ts
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/rescan.ts
  mobile/src/modules/scanning/hooks/useOnboarding.ts
  mobile/src/queries/playlist.ts
  mobile/src/queries/track.ts
  mobile/src/screens/Sheets/Backup/data.ts
  mobile/src/screens/Sheets/Track.tsx
  mobile/src/services/RNTPService.ts
  mobile/src/services/UserPreferences.ts
Labels: Housekeeping

#117 feat: Support additional track metadata
  mobile/src/api/album.ts
  mobile/src/app/current-track.tsx
  mobile/src/components/TopAppBar.tsx
  mobile/src/db/drizzle/0005_nappy_talon.sql
  mobile/src/db/drizzle/meta/0005_snapshot.json
  mobile/src/db/drizzle/meta/_journal.json
  mobile/src/db/drizzle/migrations.js
  mobile/src/db/schema.ts
  mobile/src/modules/scanning/constants.ts
  mobile/src/modules/scanning/helpers/artwork.ts
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/migrations.ts
  mobile/src/modules/scanning/helpers/rescan.ts
  mobile/src/queries/track.ts
  mobile/src/screens/Sheets/Track.tsx
  mobile/src/utils/number.ts
Labels: enhancement

#118 chore: Updated designs for "current media" screens
  mobile/src/app/(main)/(current)/_layout.tsx
  mobile/src/app/(main)/(current)/album/[id].tsx
  mobile/src/app/(main)/(current)/artist/[id].tsx
  mobile/src/app/(main)/(current)/playlist/Favorite Tracks.tsx
  mobile/src/app/(main)/(current)/playlist/[id].tsx
  mobile/src/app/(main)/(home)/artist.tsx
  mobile/src/app/(main)/(home)/folder.tsx
  mobile/src/app/(main)/(home)/index.tsx
  mobile/src/app/current-track.tsx
  mobile/src/components/Containment/Divider.tsx
  mobile/src/components/Transition/Back.tsx
  mobile/src/components/Transition/Loading.tsx
  mobile/src/components/Transition/index.ts
  mobile/src/components/Typography/StyledText.tsx
  mobile/src/components/Typography/index.ts
  mobile/src/db/utils.ts
  mobile/src/icons/Edit.tsx
  mobile/src/icons/index.ts
  mobile/src/layouts/CurrentList.tsx
  mobile/src/modules/media/components/MediaCard.tsx
  mobile/src/modules/media/components/MediaListControls.tsx
  mobile/src/modules/media/components/Track.tsx
  mobile/src/modules/search/components/SearchEngine.tsx
  mobile/src/queries/playlist.ts
  mobile/src/screens/Sheets/Track.tsx
  mobile/src/screens/Sheets/TrackToPlaylist.tsx
  mobile/src/screens/Sheets/TrackUpcoming.tsx
  mobile/src/utils/string.ts
Labels: enhancement

#119 chore: Consistent & simpler props & components
  mobile/src/app/(main)/(current)/album/[id].tsx
  mobile/src/app/(main)/(current)/artist/[id].tsx
  mobile/src/app/(main)/(current)/playlist/Favorite Tracks.tsx
  mobile/src/app/(main)/(current)/playlist/[id].tsx
  mobile/src/app/(main)/(home)/album.tsx
  mobile/src/app/(main)/(home)/artist.tsx
  mobile/src/app/(main)/(home)/folder.tsx
  mobile/src/app/(main)/(home)/index.tsx
  mobile/src/app/(main)/(home)/playlist.tsx
  mobile/src/app/(main)/(home)/track.tsx
  mobile/src/app/(main)/_layout.tsx
  mobile/src/app/+not-found.tsx
  mobile/src/app/current-track.tsx
  mobile/src/app/setting/appearance.tsx
  mobile/src/app/setting/index.tsx
  mobile/src/app/setting/insights/index.tsx
  mobile/src/app/setting/insights/save-errors.tsx
  mobile/src/app/setting/scanning.tsx
  mobile/src/app/setting/third-party/[id].tsx
  mobile/src/app/setting/update.tsx
  mobile/src/components/Containment/List.tsx
  mobile/src/components/Defaults.tsx
  mobile/src/components/Form/Legend.tsx
  mobile/src/components/Sheet/Sheet.tsx
  mobile/src/components/Transition/Placeholder.tsx
  mobile/src/components/Transition/index.ts
  mobile/src/components/Typography/AccentText.tsx
  mobile/src/components/Typography/StyledText.tsx
  mobile/src/components/Typography/index.ts
  mobile/src/db/utils.ts
  mobile/src/layouts/CurrentList.tsx
  mobile/src/layouts/Issue.tsx
  mobile/src/layouts/StandardScroll.tsx
  mobile/src/layouts/StickyActionScroll.tsx
  mobile/src/modules/media/components/MediaCard.tsx
  mobile/src/modules/media/components/Track.tsx
  mobile/src/modules/media/components/index.ts
  mobile/src/modules/search/components/SearchEngine.tsx
  mobile/src/modules/search/components/SearchResult.tsx
  mobile/src/screens/Onboarding.tsx
  mobile/src/screens/Sheets/Backup/index.tsx
  mobile/src/screens/Sheets/Font.tsx
  mobile/src/screens/Sheets/Language.tsx
  mobile/src/screens/Sheets/MinDuration.tsx
  mobile/src/screens/Sheets/ScanFilterList/index.tsx
  mobile/src/screens/Sheets/Theme.tsx
  mobile/src/screens/Sheets/Track.tsx
  mobile/src/screens/Sheets/TrackSort.tsx
  mobile/src/screens/Sheets/TrackToPlaylist.tsx
  mobile/src/screens/Sheets/TrackUpcoming.tsx
  mobile/src/screens/Sheets/index.ts
Labels: Housekeeping

#120 feat: Artwork sheet & support artist artwork
  docs/supported-gestures.md
  mobile/src/api/artist.ts
  mobile/src/api/playlist.ts
  mobile/src/api/track.ts
  mobile/src/app/(main)/(current)/artist/[id].tsx
  mobile/src/app/(main)/(home)/artist.tsx
  mobile/src/db/drizzle/0006_slow_deathstrike.sql
  mobile/src/db/drizzle/meta/0006_snapshot.json
  mobile/src/db/drizzle/meta/_journal.json
  mobile/src/db/drizzle/migrations.js
  mobile/src/db/schema.ts
  mobile/src/db/utils.ts
  mobile/src/layouts/CurrentList.tsx
  mobile/src/lib/file-system.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/modules/scanning/helpers/artwork.ts
  mobile/src/modules/search/components/SearchEngine.tsx
  mobile/src/queries/album.ts
  mobile/src/queries/artist.ts
  mobile/src/queries/playlist.ts
  mobile/src/screens/Sheets/Artwork.tsx
  mobile/src/screens/Sheets/index.ts
  mobile/src/utils/string.ts
Labels: enhancement

#121 chore: Re-add ability to create playlists
  mobile/src/api/playlist.ts
  mobile/src/app/(main)/(current)/_layout.tsx
  mobile/src/app/(main)/(current)/playlist/create.tsx
  mobile/src/app/(main)/(home)/folder.tsx
  mobile/src/app/(main)/(home)/playlist.tsx
  mobile/src/app/(main)/_layout.tsx
  mobile/src/components/TopAppBar.tsx
  mobile/src/db/utils.ts
  mobile/src/hooks/useBottomActionsContext.ts
  mobile/src/icons/Cancel.tsx
  mobile/src/icons/Check.tsx
  mobile/src/icons/CheckCircle.tsx
  mobile/src/icons/index.ts
  mobile/src/lib/react-query.ts
  mobile/src/modules/media/components/MiniPlayer.tsx
  mobile/src/modules/media/constants.ts
  mobile/src/modules/search/components/SearchEngine.tsx
  mobile/src/queries/playlist.ts
  mobile/src/screens/ModifyPlaylist.tsx
  mobile/src/screens/Sheets/AddMusic.tsx
  mobile/src/screens/Sheets/index.ts
Labels: enhancement

#122 chore: Re-add ability to edit & delete playlists
  mobile/src/api/playlist.ts
  mobile/src/app/(main)/(current)/_layout.tsx
  mobile/src/app/(main)/(current)/playlist/[id].tsx
  mobile/src/app/(main)/(current)/playlist/modify.tsx
  mobile/src/modules/media/services/Music.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/modules/media/services/Resynchronize.ts
  mobile/src/queries/playlist.ts
  mobile/src/screens/ModifyPlaylist.tsx
Labels: enhancement

#127 feat: Support custom track order in playlist
  THIRD_PARTY.md
  docs/supported-gestures.md
  mobile/package.json
  mobile/patches/react-native-gesture-handler@2.21.2.patch
  mobile/pnpm-lock.yaml
  mobile/src/api/playlist.ts
  mobile/src/api/track.ts
  mobile/src/app/(main)/(current)/playlist/[id].tsx
  mobile/src/app/(main)/(current)/playlist/create.tsx
  mobile/src/app/(main)/(current)/playlist/modify.tsx
  mobile/src/components/Form/Button.tsx
  mobile/src/components/Form/index.ts
  mobile/src/components/Swipeable.tsx
  mobile/src/db/drizzle/0005_equal_cerise.sql
  mobile/src/db/drizzle/0006_slow_deathstrike.sql
  mobile/src/db/drizzle/meta/0005_snapshot.json
  mobile/src/db/drizzle/meta/0006_snapshot.json
  mobile/src/db/drizzle/meta/_journal.json
  mobile/src/db/drizzle/migrations.js
  mobile/src/db/schema.ts
  mobile/src/layouts/CurrentList.tsx
  mobile/src/modules/media/components/Track.tsx
  mobile/src/modules/scanning/helpers/folder.ts
  mobile/src/modules/scanning/helpers/migrations.ts
  mobile/src/modules/search/components/SearchResult.tsx
  mobile/src/queries/playlist.ts
  mobile/src/resources/licenses.json
  mobile/src/screens/ModifyPlaylist.tsx
  mobile/src/screens/ModifyPlaylist/context.tsx
  mobile/src/screens/ModifyPlaylist/index.tsx
  mobile/src/screens/Sheets/TrackToPlaylist.tsx
  mobile/src/utils/types.ts
Labels: enhancement

#126 i18n: Update de.json to include the common.* added in december
  mobile/src/modules/i18n/translations/de.json
Labels: Translations

#128 feat: Add "Repeat One" mode
  mobile/src/icons/RepeatOne.tsx
  mobile/src/icons/index.ts
  mobile/src/modules/i18n/CHANGELOG.md
  mobile/src/modules/i18n/translations/en.json
  mobile/src/modules/media/components/MediaControls.tsx
  mobile/src/modules/media/services/Music.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/screens/Sheets/TrackUpcoming.tsx
  mobile/src/services/RNTPService.ts
Labels: enhancement

#129 perf: Optimized SQL queries for indexing logic
  mobile/src/modules/scanning/helpers/artwork.ts
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/rescan.ts
  mobile/src/utils/promise.ts
Labels: Housekeeping
