Repository MissingCore/Music, pull requests merged in 2025-08, with the labels that each got.

#259 feat: Support tracking recently played tracks
  mobile/src/api/recent.ts
  mobile/src/app/(main)/(current)/_layout.tsx
  mobile/src/app/(main)/(current)/recently-played.tsx
  mobile/src/app/(main)/(home)/index.tsx
  mobile/src/app/setting/appearance/index.tsx
  mobile/src/db/drizzle/0010_steep_shinko_yamashiro.sql
  mobile/src/db/drizzle/meta/0010_snapshot.json
  mobile/src/db/drizzle/meta/_journal.json
  mobile/src/db/drizzle/migrations.js
  mobile/src/db/schema.ts
  mobile/src/hooks/useBottomActionsContext.ts
  mobile/src/hooks/useSetup.ts
  mobile/src/icons/History.tsx
  mobile/src/layouts/StandardScroll.tsx
  mobile/src/modules/i18n/translations/en.json
  mobile/src/modules/media/helpers/data.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/modules/media/services/RecentList.ts
  mobile/src/modules/media/services/Resynchronize.ts
  mobile/src/modules/scanning/constants.ts
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/migrations.ts
  mobile/src/modules/scanning/helpers/rescan.ts
  mobile/src/queries/album.ts
  mobile/src/queries/artist.ts
  mobile/src/queries/keyStore.ts
  mobile/src/queries/playlist.ts
  mobile/src/queries/recent.ts
  mobile/src/queries/track.ts
  mobile/src/screens/Sheets/Settings/helpers/BackupData.ts
  mobile/src/services/RNTPService.ts
  mobile/src/services/UserPreferences.ts
Labels: enhancement

#260 refactor: Improve performance of `savePathComponents()`
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/folder.ts
  mobile/src/modules/scanning/helpers/migrations.ts
  mobile/src/modules/scanning/helpers/rescan.ts
Labels: Housekeeping

#264 feat: Ability to change the tab displayed on app launch
  mobile/src/app/(main)/(home)/index.tsx
  mobile/src/app/setting/appearance/home-tabs-order.tsx
  mobile/src/icons/Home.tsx
  mobile/src/modules/i18n/translations/en.json
  mobile/src/services/UserPreferences.ts
Labels: enhancement

#266 i18n: Polish translation update
  mobile/src/modules/i18n/translations/pl.json
Labels: Translations
