Repository MissingCore/Music, pull requests merged in 2025-02, with the labels that each got.

#161 fix: Duplicate albums caused by album not having an associated year
  mobile/src/app/(main)/(current)/artist/[id].tsx
  mobile/src/db/drizzle/0006_wild_gabe_jones.sql
  mobile/src/db/drizzle/meta/0006_snapshot.json
  mobile/src/db/drizzle/meta/_journal.json
  mobile/src/db/drizzle/migrations.js
  mobile/src/db/schema.ts
  mobile/src/db/utils.ts
  mobile/src/modules/scanning/constants.ts
  mobile/src/modules/scanning/helpers/_album-fracturization.ts
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/migrations.ts
  mobile/src/utils/number.ts
  mobile/src/utils/string.ts
Labels: Bug

#162 perf: Improve search modal open speed for users with lots of tracks
  mobile/src/api/playlist.ts
  mobile/src/api/track.ts
  mobile/src/db/slimTypes.ts
  mobile/src/db/utils.ts
  mobile/src/modules/search/components/SearchEngine.tsx
  mobile/src/modules/search/hooks/useSearch.ts
  mobile/src/modules/search/types.ts
  mobile/src/queries/playlist.ts
  mobile/src/screens/ModifyPlaylist/context.tsx
  mobile/src/screens/ModifyPlaylist/index.tsx
Labels: Housekeeping

#163 chore: Restructure "Music" store & fix some flakey code
  mobile/src/modules/media/helpers/data.ts
  mobile/src/modules/media/services/Music.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/modules/media/services/_subscriptions.ts
  mobile/src/providers/index.tsx
  mobile/src/screens/Sheets/TrackUpcoming/context.tsx
  mobile/src/screens/Sheets/TrackUpcoming/index.tsx
  mobile/src/services/RNTPService.ts
Labels: Housekeeping

#164 Add Deep scan Japanese text.
  mobile/src/modules/i18n/translations/ja.json
Labels: Translations

#166 i18n(ca): Add Catalan Translation
  README.md
  mobile/src/modules/i18n/constants.ts
  mobile/src/modules/i18n/index.ts
  mobile/src/modules/i18n/translations/ca.json
Labels: Translations

#167 Adding Hindi Translation
  README.md
  mobile/src/modules/i18n/constants.ts
  mobile/src/modules/i18n/index.ts
  mobile/src/modules/i18n/translations/hi.json
Labels: Translations

#176 i18n: Revised translation structure (that doesn't dangerously break things)
  mobile/scripts/translation-migration/README.md
  mobile/scripts/translation-migration/index.mjs
  mobile/scripts/translation-migration/newStructure.json
  mobile/scripts/translation-migration/translationMap.json
  mobile/src/modules/i18n/translations/ca.json
  mobile/src/modules/i18n/translations/ca/base.json
  mobile/src/modules/i18n/translations/ca/error.json
  mobile/src/modules/i18n/translations/ca/feature.json
  mobile/src/modules/i18n/translations/de.json
  mobile/src/modules/i18n/translations/de/base.json
  mobile/src/modules/i18n/translations/de/error.json
  mobile/src/modules/i18n/translations/de/feature.json
  mobile/src/modules/i18n/translations/en.json
  mobile/src/modules/i18n/translations/en/base.json
  mobile/src/modules/i18n/translations/en/error.json
  mobile/src/modules/i18n/translations/en/feature.json
  mobile/src/modules/i18n/translations/es.json
  mobile/src/modules/i18n/translations/es/base.json
  mobile/src/modules/i18n/translations/es/error.json
  mobile/src/modules/i18n/translations/es/feature.json
  mobile/src/modules/i18n/translations/fr.json
  mobile/src/modules/i18n/translations/fr/base.json
  mobile/src/modules/i18n/translations/fr/error.json
  mobile/src/modules/i18n/translations/fr/feature.json
  mobile/src/modules/i18n/translations/hi.json
  mobile/src/modules/i18n/translations/hi/base.json
  mobile/src/modules/i18n/translations/hi/error.json
  mobile/src/modules/i18n/translations/hi/feature.json
  mobile/src/modules/i18n/translations/id.json
  mobile/src/modules/i18n/translations/id/base.json
  mobile/src/modules/i18n/translations/id/error.json
  mobile/src/modules/i18n/translations/id/feature.json
  mobile/src/modules/i18n/translations/ja.json
  mobile/src/modules/i18n/translations/ja/base.json
  mobile/src/modules/i18n/translations/ja/error.json
  mobile/src/modules/i18n/translations/ja/feature.json
  mobile/src/modules/i18n/translations/ru.json
  mobile/src/modules/i18n/translations/ru/base.json
  mobile/src/modules/i18n/translations/ru/error.json
  mobile/src/modules/i18n/translations/ru/feature.json
  mobile/src/modules/i18n/translations/tr.json
  mobile/src/modules/i18n/translations/tr/base.json
  mobile/src/modules/i18n/translations/tr/error.json
  mobile/src/modules/i18n/translations/tr/feature.json
  mobile/src/modules/i18n/translations/zh-Hans.json
  mobile/src/modules/i18n/translations/zh-Hans/base.json
  mobile/src/modules/i18n/translations/zh-Hans/error.json
  mobile/src/modules/i18n/translations/zh-Hans/feature.json
Labels: Translations

#182 feat: Simpler Privacy Build
  .github/workflows/latest-stable-branch.yml
  .github/workflows/privacy-build.yml
  docs/assets/personal-privacy-build/build_apk_1.jpg
  docs/assets/personal-privacy-build/build_apk_1.png
  docs/assets/personal-privacy-build/create_latest_stable_branch.png
  docs/assets/personal-privacy-build/forking_1.jpg
  docs/assets/personal-privacy-build/forking_1.png
  docs/assets/personal-privacy-build/forking_2.jpg
  docs/assets/personal-privacy-build/forking_2.png
  docs/assets/personal-privacy-build/personal_access_token_1.png
  docs/assets/personal-privacy-build/personal_access_token_2.png
  docs/assets/personal-privacy-build/personal_access_token_3.png
  docs/assets/personal-privacy-build/personal_access_token_4.png
  docs/assets/personal-privacy-build/personal_access_token_5.png
  docs/assets/personal-privacy-build/remove_sentry_1.png
  docs/assets/personal-privacy-build/remove_sentry_2.png
  docs/assets/personal-privacy-build/remove_sentry_3.png
  docs/assets/personal-privacy-build/remove_sentry_4.png
  docs/assets/personal-privacy-build/remove_sentry_5.png
  docs/personal-privacy-build.md
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/metro.config.js
  mobile/package.json
  mobile/pnpm-lock.yaml
  mobile/src/app/_layout.tsx
  mobile/src/resources/licenses.json
Labels: enhancement

#186 chore: Option to use "old" v1 vinyl design on the "Now Playing" screen
  mobile/src/app/_layout.tsx
  mobile/src/app/now-playing.tsx
  mobile/src/components/Containment/SafeContainer.tsx
  mobile/src/components/TopAppBar.tsx
  mobile/src/screens/NowPlaying/Artwork.tsx
  mobile/src/services/UserPreferences.ts
Labels: enhancement
