Repository MissingCore/Music, pull requests merged in 2025-06, with the labels that each got.

#240 chore(deps): Update to RN 0.79 & Expo SDK 53
  THIRD_PARTY.md
  mobile/.eslintrc.js
  mobile/android/app/build.gradle
  mobile/android/app/src/main/java/com/cyanchill/missingcore/music/MainApplication.kt
  mobile/android/app/src/main/res/values/styles.xml
  mobile/android/build.gradle
  mobile/android/gradle.properties
  mobile/android/gradle/wrapper/gradle-wrapper.properties
  mobile/android/gradlew
  mobile/android/settings.gradle
  mobile/app.config.ts
  mobile/eslint.config.js
  mobile/index.ts
  mobile/package.json
  mobile/patches/react-native-reanimated.patch
  mobile/pnpm-lock.yaml
  mobile/scripts/licenses/licenseClarification.json
  mobile/src/app/(main)/(home)/_layout.tsx
  mobile/src/app/_layout.tsx
  mobile/src/components/Defaults.tsx
  mobile/src/components/Form/Input.tsx
  mobile/src/components/Sheet.tsx
  mobile/src/components/Transition/Back.tsx
  mobile/src/hooks/useLoadResources.ts
  mobile/src/layouts/StickyActionScroll.tsx
  mobile/src/lib/file-system.ts
  mobile/src/lib/sentry.ts
  mobile/src/modules/media/services/Playback.ts
  mobile/src/modules/scanning/constants.ts
  mobile/src/modules/scanning/helpers/artwork.ts
  mobile/src/providers/ThemeProvider.tsx
  mobile/src/resources/licenses.json
  mobile/src/screens/ErrorBoundary.tsx
  mobile/src/screens/ModifyPlaylist/context.tsx
  mobile/src/screens/NowPlaying/helpers/usePlayerProgress.ts
  mobile/src/screens/Sheets/Settings/helpers/BackupData.ts
Labels: dependencies, Housekeeping

#242 i18n: Polish translation update
  mobile/src/modules/i18n/translations/pl.json
Labels: Translations

#244 feat: Local metadata editor
  THIRD_PARTY.md
  mobile/package.json
  mobile/pnpm-lock.yaml
  mobile/src/app/(main)/(current)/_layout.tsx
  mobile/src/app/(main)/(current)/track/modify.tsx
  mobile/src/components/Modal.tsx
  mobile/src/db/drizzle/0009_ambitious_puppet_master.sql
  mobile/src/db/drizzle/meta/0009_snapshot.json
  mobile/src/db/drizzle/meta/_journal.json
  mobile/src/db/drizzle/migrations.js
  mobile/src/db/schema.ts
  mobile/src/hooks/useBottomActionsContext.ts
  mobile/src/icons/Image.tsx
  mobile/src/modules/i18n/translations/en.json
  mobile/src/modules/scanning/helpers/artwork.ts
  mobile/src/modules/scanning/helpers/audio.ts
  mobile/src/modules/scanning/helpers/rescan.ts
  mobile/src/providers/index.tsx
  mobile/src/queries/track.ts
  mobile/src/resources/licenses.json
  mobile/src/screens/ModifyPlaylist/index.tsx
  mobile/src/screens/ModifyTrack/context.tsx
  mobile/src/screens/ModifyTrack/index.tsx
  mobile/src/screens/Sheets/Artwork.tsx
  mobile/src/screens/Sheets/Track.tsx
Labels: enhancement

#245 fix: Synchronize store w/ metadata change
  mobile/src/modules/media/helpers/revalidate.ts
  mobile/src/queries/album.ts
  mobile/src/queries/track.ts
  mobile/src/screens/ModifyTrack/context.tsx
Labels: Housekeeping

#246 fix: Sheet gesture not working with scrollable child with `nestedScrollEnabled`
  mobile/src/components/Defaults.tsx
  mobile/src/screens/Sheets/Settings/Root.tsx
  mobile/src/screens/Sheets/Track.tsx
Labels: Bug: UI
